### ISSUE TITLE
Issue with running speed

### ISSUE THREAD

**Issue by ghost** [backdaniel/essentials_move#2]
Hi,

I'm using Stamina mods for running, one with hunger, one without hunger and if I enable "movement_essentials" the running speed get reduced to walking speed, as if there was no stamina mod in use.

Thats all.

**Comment by backdaniel** [comment]
fixed, i tested with https://content.minetest.net/packages/sofar/stamina/ https://content.minetest.net/packages/TenPlus1/stamina/ https://content.minetest.net/packages/nekobit/real_stamina/ and they all seem to work now

**Comment by backdaniel** [comment]
fixed, i tested with https://content.minetest.net/packages/sofar/stamina/ https://content.minetest.net/packages/TenPlus1/stamina/ https://content.minetest.net/packages/nekobit/real_stamina/ and they all seem to work now
